services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  authservice:
    build:
      context: ./backend
      dockerfile: SayPostAuthService/src/SayPostAuthService.Api/Dockerfile
    ports:
      - "5177:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceName=SayPostAuthService
      - ConnectionStrings__AuthServiceDb=Host=postgres;Port=5432;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=saypost_auth_service_db;SslMode=Disable;Include Error Detail=true
      - RabbitMq__Host=${RABBITMQ_HOST}
      - RabbitMq__Username=${RABBITMQ_USER}
      - RabbitMq__Password=${RABBITMQ_PASSWORD}
      - JwtTokenConfig__Issuer=${JWT_ISSUER}
      - JwtTokenConfig__Audience=${JWT_AUDIENCE}
      - JwtTokenConfig__SecretKey=${JWT_SECRET}
      - MessageBroker__QueueName=${RABBITMQ_QUEUE_AUTH}
      - MessageBroker__ExchangeName=${RABBITMQ_EXCHANGE}

  mainservice:
    build:
      context: ./backend
      dockerfile: SayPostMainService/src/SayPostMainService.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceName=SayPostMainService
      - ConnectionStrings__MainServiceDb=Host=postgres;Port=5432;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=saypost_main_service_db;SslMode=Disable;Include Error Detail=true
      - ConnectionStrings__FollowingServiceDb=Host=postgres;Port=5432;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=saypost_following_service_db;SslMode=Disable;Include Error Detail=true
      - MessageBroker__HostName=${RABBITMQ_HOST}
      - MessageBroker__Port=5672
      - MessageBroker__UserName=${RABBITMQ_USER}
      - MessageBroker__Password=${RABBITMQ_PASSWORD}
      - JwtTokenConfig__Issuer=${JWT_ISSUER}
      - JwtTokenConfig__Audience=${JWT_AUDIENCE}
      - JwtTokenConfig__SecretKey=${JWT_SECRET}
      - MessageBroker__QueueName=${RABBITMQ_QUEUE_MAIN}
      - MessageBroker__ExchangeName=${RABBITMQ_EXCHANGE}

  followingsservice:
    build:
      context: ./backend
      dockerfile: SayPostFollowingsService/src/SayPostFollowingsService.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceName=SayPostFollowingsService
      - ConnectionStrings__FollowingServiceDb=Host=postgres;Port=5432;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=saypost_following_service_db;SslMode=Disable;Include Error Detail=true
      - MessageBroker__HostName=${RABBITMQ_HOST}
      - MessageBroker__Port=5672
      - MessageBroker__UserName=${RABBITMQ_USER}
      - MessageBroker__Password=${RABBITMQ_PASSWORD}
      - JwtTokenConfig__Issuer=${JWT_ISSUER}
      - JwtTokenConfig__Audience=${JWT_AUDIENCE}
      - JwtTokenConfig__SecretKey=${JWT_SECRET}
      - MessageBroker__QueueName=${RABBITMQ_QUEUE_FOLLOWING}
      - MessageBroker__ExchangeName=${RABBITMQ_EXCHANGE}

  notificationservice:
    build:
      context: ./backend
      dockerfile: SayPostNotificationService/src/SayPostNotificationService.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceName=SayPostNotificationsService
      - ConnectionStrings__NotificationServiceDb=Host=postgres;Port=5432;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=saypost_notification_service_db;SslMode=Disable;Include Error Detail=true
      - ConnectionStrings__FollowingServiceDb=Host=postgres;Port=5432;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=saypost_following_service_db;SslMode=Disable;Include Error Detail=true
      - MessageBroker__HostName=${RABBITMQ_HOST}
      - MessageBroker__Port=5672
      - MessageBroker__UserName=${RABBITMQ_USER}
      - MessageBroker__Password=${RABBITMQ_PASSWORD}
      - JwtTokenConfig__Issuer=${JWT_ISSUER}
      - JwtTokenConfig__Audience=${JWT_AUDIENCE}
      - JwtTokenConfig__SecretKey=${JWT_SECRET}
      - MessageBroker__QueueName=${RABBITMQ_QUEUE_NOTIFICATION}
      - MessageBroker__ExchangeName=${RABBITMQ_EXCHANGE}

volumes:
  pgdata:
  rabbitmq_data:
